name: CI Pipeline - Docker Build, Scan & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ğŸ” Trivy filesystem scan (code + Dockerfile)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      # ğŸ”‘ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ğŸ— Build Docker image
      - name: Build Docker image
        run: |
          docker build -t sachinteenwal/devops-demo-backend:latest .

      # ğŸ” Trivy Image Scan
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: sachinteenwal/devops-demo-backend:latest
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      # ğŸš€ Push Docker image
      - name: Push Docker image
        run: |
          docker push sachinteenwal/devops-demo-backend:latest
