name: CI - Build, Scan, Push & Update GitOps

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sachinteenwal/devops-demo-backend
  GITOPS_REPO: sachinteenwal/Gitops-K8s-Deployment-P2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: Sachintee/Gitops-K8s-Deployment-P2
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops



      - name: Update Image Tag in Deployment
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|" gitops/deployment.yaml

      - name: Commit & Push GitOps Change
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to $IMAGE_NAME:$IMAGE_TAG"
          git push
